/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLy.GUI;

import MyCustom.MyDialog;
import MyCustom.MyTable;
import MyCustom.ImagePanel;

import QuanLy.BUS.NhanVienBUS;
import QuanLy.BUS.PhanQuyenBUS;
import QuanLy.BUS.TaiKhoanBUS;
import QuanLy.DTO.NhanVien;
import QuanLy.DTO.PhanQuyen;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pero
 */
public class FormNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form FormNhanVien
     */
    public FormNhanVien() {
        initComponents();
        loadDataTblNhanVien();
        loadDataCmbQuyen();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        form_quanlynhanvien = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbGioiTinh = new javax.swing.JComboBox<>();
        txtChucVu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtHo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        pnThemNV = new javax.swing.JPanel();
        btnThemNV = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnSuaNV = new javax.swing.JPanel();
        btnSuaNV = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pnXoaNV = new javax.swing.JPanel();
        btnXoaNV = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtTimNV = new javax.swing.JTextField();
        pnTimNV = new javax.swing.JPanel();
        btnTimNV = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        pnCapTaiKhoan = new javax.swing.JPanel();
        btnCapTaiKhoan = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        pnResetMatKhau = new javax.swing.JPanel();
        btnResetQuyenMatKhau = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhanVien = new MyCustom.MyTable();
        btnReset = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnKhoaTaiKhoan = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        form_phanquyen = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cmbQuyen = new javax.swing.JComboBox<>();
        ckbNhapHang = new javax.swing.JCheckBox();
        ckbQLSanPham = new javax.swing.JCheckBox();
        ckbThongKe = new javax.swing.JCheckBox();
        ckbQLNhanVien = new javax.swing.JCheckBox();
        ckbQLKhachHang = new javax.swing.JCheckBox();
        pnSuaQuyen = new javax.swing.JPanel();
        btnSuaQuyen = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        pnXoaQuyen = new javax.swing.JPanel();
        btnXoaQuyen = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        bpnThemQuyen = new javax.swing.JPanel();
        btnThemQuyen = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N

        form_quanlynhanvien.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel3.setText("Mã nhân viên:");

        txtMaNV.setEditable(false);
        txtMaNV.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        txtMaNV.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel6.setText("Giới tính:");

        cmbGioiTinh.setEditable(true);
        cmbGioiTinh.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        cmbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn giới tính", "Nam", "Nữ" }));

        txtChucVu.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel7.setText("Chức vụ:");

        txtHo.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel5.setText("Họ và tên đệm:");

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel11.setText("Tên:");

        txtTen.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N

        pnThemNV.setBackground(new java.awt.Color(4, 110, 57));
        pnThemNV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnThemNV.setBackground(new java.awt.Color(8, 130, 44));
        btnThemNV.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnThemNV.setForeground(new java.awt.Color(255, 255, 255));
        btnThemNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThemNV.setText("Thêm");
        btnThemNV.setToolTipText("");
        btnThemNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemNVMouseClicked(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(".\\image\\add.png"));

        javax.swing.GroupLayout pnThemNVLayout = new javax.swing.GroupLayout(pnThemNV);
        pnThemNV.setLayout(pnThemNVLayout);
        pnThemNVLayout.setHorizontalGroup(
            pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThemNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnThemNVLayout.setVerticalGroup(
            pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnSuaNV.setBackground(new java.awt.Color(220, 128, 37));
        pnSuaNV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnSuaNV.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnSuaNV.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSuaNV.setText("Sửa");
        btnSuaNV.setToolTipText("");
        btnSuaNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaNVMouseClicked(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(".\\image\\edit.png"));

        javax.swing.GroupLayout pnSuaNVLayout = new javax.swing.GroupLayout(pnSuaNV);
        pnSuaNV.setLayout(pnSuaNVLayout);
        pnSuaNVLayout.setHorizontalGroup(
            pnSuaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSuaNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSuaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnSuaNVLayout.setVerticalGroup(
            pnSuaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSuaNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSuaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSuaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnXoaNV.setBackground(new java.awt.Color(173, 36, 36));
        pnXoaNV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnXoaNV.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnXoaNV.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnXoaNV.setText("Xóa ");
        btnXoaNV.setToolTipText("");
        btnXoaNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaNVMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(".\\image\\delete.png"));

        javax.swing.GroupLayout pnXoaNVLayout = new javax.swing.GroupLayout(pnXoaNV);
        pnXoaNV.setLayout(pnXoaNVLayout);
        pnXoaNVLayout.setHorizontalGroup(
            pnXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnXoaNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnXoaNVLayout.setVerticalGroup(
            pnXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXoaNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel44.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel44.setText("Tìm nhân viên:");

        txtTimNV.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        pnTimNV.setBackground(new java.awt.Color(51, 51, 51));
        pnTimNV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnTimNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTimNV.setIcon(new javax.swing.ImageIcon(".\\image\\search.png"));

        javax.swing.GroupLayout pnTimNVLayout = new javax.swing.GroupLayout(pnTimNV);
        pnTimNV.setLayout(pnTimNVLayout);
        pnTimNVLayout.setHorizontalGroup(
            pnTimNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTimNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTimNV, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTimNVLayout.setVerticalGroup(
            pnTimNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTimNV, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnCapTaiKhoan.setBackground(new java.awt.Color(0, 51, 51));
        pnCapTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnCapTaiKhoan.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnCapTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btnCapTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCapTaiKhoan.setText("Cấp tài khoản");
        btnCapTaiKhoan.setToolTipText("");
        btnCapTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCapTaiKhoanMouseClicked(evt);
            }
        });

        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setIcon(new javax.swing.ImageIcon(".\\image\\add-account.png"));

        javax.swing.GroupLayout pnCapTaiKhoanLayout = new javax.swing.GroupLayout(pnCapTaiKhoan);
        pnCapTaiKhoan.setLayout(pnCapTaiKhoanLayout);
        pnCapTaiKhoanLayout.setHorizontalGroup(
            pnCapTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCapTaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCapTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnCapTaiKhoanLayout.setVerticalGroup(
            pnCapTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCapTaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCapTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCapTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnResetMatKhau.setBackground(new java.awt.Color(51, 0, 51));
        pnResetMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnResetQuyenMatKhau.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnResetQuyenMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        btnResetQuyenMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnResetQuyenMatKhau.setText("Quyền/Mật khẩu");
        btnResetQuyenMatKhau.setToolTipText("");
        btnResetQuyenMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetQuyenMatKhauMouseClicked(evt);
            }
        });

        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setIcon(new javax.swing.ImageIcon(".\\image\\password.png"));

        javax.swing.GroupLayout pnResetMatKhauLayout = new javax.swing.GroupLayout(pnResetMatKhau);
        pnResetMatKhau.setLayout(pnResetMatKhauLayout);
        pnResetMatKhauLayout.setHorizontalGroup(
            pnResetMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnResetMatKhauLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResetQuyenMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnResetMatKhauLayout.setVerticalGroup(
            pnResetMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnResetMatKhauLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnResetMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnResetQuyenMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Họ và tên đệm", "Tên", "Giới tính", "Chức vụ", "Tài khoản"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.setRowHeight(35);
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNhanVien);
        if (tblNhanVien.getColumnModel().getColumnCount() > 0) {
            tblNhanVien.getColumnModel().getColumn(0).setMaxWidth(75);
            tblNhanVien.getColumnModel().getColumn(1).setMaxWidth(300);
            tblNhanVien.getColumnModel().getColumn(2).setMaxWidth(300);
            tblNhanVien.getColumnModel().getColumn(3).setMaxWidth(200);
            tblNhanVien.getColumnModel().getColumn(4).setMaxWidth(200);
            tblNhanVien.getColumnModel().getColumn(5).setMaxWidth(300);
        }

        btnReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnKhoaTaiKhoan.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnKhoaTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btnKhoaTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnKhoaTaiKhoan.setText("Khóa tài khoản");
        btnKhoaTaiKhoan.setToolTipText("");
        btnKhoaTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKhoaTaiKhoanMouseClicked(evt);
            }
        });

        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setIcon(new javax.swing.ImageIcon(".\\image\\lock.png"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKhoaTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKhoaTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout form_quanlynhanvienLayout = new javax.swing.GroupLayout(form_quanlynhanvien);
        form_quanlynhanvien.setLayout(form_quanlynhanvienLayout);
        form_quanlynhanvienLayout.setHorizontalGroup(
            form_quanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_quanlynhanvienLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(form_quanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, form_quanlynhanvienLayout.createSequentialGroup()
                        .addComponent(jSeparator4)
                        .addGap(23, 23, 23))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1062, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(form_quanlynhanvienLayout.createSequentialGroup()
                        .addGroup(form_quanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(form_quanlynhanvienLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(pnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnSuaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnCapTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnResetMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(form_quanlynhanvienLayout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTimNV, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnTimNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(451, 451, 451)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(form_quanlynhanvienLayout.createSequentialGroup()
                        .addGroup(form_quanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(form_quanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTen)
                            .addComponent(txtHo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(form_quanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(33, 33, 33)
                        .addGroup(form_quanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtChucVu)
                            .addComponent(cmbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        form_quanlynhanvienLayout.setVerticalGroup(
            form_quanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_quanlynhanvienLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(form_quanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(form_quanlynhanvienLayout.createSequentialGroup()
                        .addGroup(form_quanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(form_quanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(form_quanlynhanvienLayout.createSequentialGroup()
                        .addGroup(form_quanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(form_quanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(form_quanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(form_quanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(form_quanlynhanvienLayout.createSequentialGroup()
                        .addGroup(form_quanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnThemNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnSuaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnXoaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnResetMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(form_quanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, form_quanlynhanvienLayout.createSequentialGroup()
                                .addComponent(pnTimNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, form_quanlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTimNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(pnCapTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        jTabbedPane1.addTab("Quản lý nhân viên", form_quanlynhanvien);

        form_phanquyen.setBackground(new java.awt.Color(255, 255, 255));

        jLabel29.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel29.setText("Nhóm quyền:");

        jLabel30.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel30.setText("Phân quyền:");

        cmbQuyen.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        cmbQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbQuyenActionPerformed(evt);
            }
        });

        ckbNhapHang.setBackground(new java.awt.Color(255, 255, 255));
        ckbNhapHang.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        ckbNhapHang.setText("Quản lý nhập hàng");
        ckbNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbNhapHangActionPerformed(evt);
            }
        });

        ckbQLSanPham.setBackground(new java.awt.Color(255, 255, 255));
        ckbQLSanPham.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        ckbQLSanPham.setText("Quản lý sản phẩm");
        ckbQLSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbQLSanPhamActionPerformed(evt);
            }
        });

        ckbThongKe.setBackground(new java.awt.Color(255, 255, 255));
        ckbThongKe.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        ckbThongKe.setText("Quản lý thống kê");
        ckbThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbThongKeActionPerformed(evt);
            }
        });

        ckbQLNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        ckbQLNhanVien.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        ckbQLNhanVien.setText("Quản lý nhân viên");
        ckbQLNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbQLNhanVienActionPerformed(evt);
            }
        });

        ckbQLKhachHang.setBackground(new java.awt.Color(255, 255, 255));
        ckbQLKhachHang.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        ckbQLKhachHang.setText("Quản lý khách hàng");
        ckbQLKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbQLKhachHangActionPerformed(evt);
            }
        });

        pnSuaQuyen.setBackground(new java.awt.Color(220, 128, 37));
        pnSuaQuyen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnSuaQuyen.setBackground(new java.awt.Color(8, 130, 44));
        btnSuaQuyen.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnSuaQuyen.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaQuyen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSuaQuyen.setText("Sửa");
        btnSuaQuyen.setToolTipText("");
        btnSuaQuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaQuyenMouseClicked(evt);
            }
        });

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(".\\image\\edit.png"));

        javax.swing.GroupLayout pnSuaQuyenLayout = new javax.swing.GroupLayout(pnSuaQuyen);
        pnSuaQuyen.setLayout(pnSuaQuyenLayout);
        pnSuaQuyenLayout.setHorizontalGroup(
            pnSuaQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSuaQuyenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSuaQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnSuaQuyenLayout.setVerticalGroup(
            pnSuaQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSuaQuyenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSuaQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSuaQuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnXoaQuyen.setBackground(new java.awt.Color(173, 36, 36));
        pnXoaQuyen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnXoaQuyen.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnXoaQuyen.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaQuyen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnXoaQuyen.setText("Xóa");
        btnXoaQuyen.setToolTipText("");
        btnXoaQuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaQuyenMouseClicked(evt);
            }
        });

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setIcon(new javax.swing.ImageIcon(".\\image\\delete.png"));

        javax.swing.GroupLayout pnXoaQuyenLayout = new javax.swing.GroupLayout(pnXoaQuyen);
        pnXoaQuyen.setLayout(pnXoaQuyenLayout);
        pnXoaQuyenLayout.setHorizontalGroup(
            pnXoaQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnXoaQuyenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnXoaQuyenLayout.setVerticalGroup(
            pnXoaQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXoaQuyenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnXoaQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoaQuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        bpnThemQuyen.setBackground(new java.awt.Color(4, 110, 57));
        bpnThemQuyen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnThemQuyen.setBackground(new java.awt.Color(8, 130, 44));
        btnThemQuyen.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnThemQuyen.setForeground(new java.awt.Color(255, 255, 255));
        btnThemQuyen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThemQuyen.setText("Thêm");
        btnThemQuyen.setToolTipText("");
        btnThemQuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemQuyenMouseClicked(evt);
            }
        });

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(".\\image\\add.png"));

        javax.swing.GroupLayout bpnThemQuyenLayout = new javax.swing.GroupLayout(bpnThemQuyen);
        bpnThemQuyen.setLayout(bpnThemQuyenLayout);
        bpnThemQuyenLayout.setHorizontalGroup(
            bpnThemQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bpnThemQuyenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThemQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bpnThemQuyenLayout.setVerticalGroup(
            bpnThemQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bpnThemQuyenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bpnThemQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemQuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout form_phanquyenLayout = new javax.swing.GroupLayout(form_phanquyen);
        form_phanquyen.setLayout(form_phanquyenLayout);
        form_phanquyenLayout.setHorizontalGroup(
            form_phanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_phanquyenLayout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addGroup(form_phanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel29))
                .addGap(46, 46, 46)
                .addGroup(form_phanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbQuyen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbQLSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbQLNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbQLKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(404, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, form_phanquyenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bpnThemQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnSuaQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnXoaQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(353, 353, 353))
        );
        form_phanquyenLayout.setVerticalGroup(
            form_phanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_phanquyenLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(form_phanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(form_phanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ckbQLSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ckbQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ckbQLKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ckbThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(form_phanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnXoaQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnSuaQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpnThemQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(318, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quyền", form_phanquyen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void xuLyXoaNhanVien() {
        String ma = txtMaNV.getText();
        boolean flag = nhanVienBUS.xoaNhanVien(ma);
        if (flag) {
            nhanVienBUS.docDanhSach();
            loadDataTblNhanVien();
        }
    }

    private void xuLySuaNhanVien() {
        if (cmbGioiTinh.getSelectedIndex() == 0) {
            new MyDialog("Hãy chọn giới tính!", MyDialog.ERROR_DIALOG);
            return;
        }
        String ma = txtMaNV.getText();
        String ho = txtHo.getText();
        String ten = txtTen.getText();
        String gioiTinh = cmbGioiTinh.getSelectedItem() + "";
        String chucVu = txtChucVu.getText();
        if (nhanVienBUS.updateNhanVien(ma, ho, ten, gioiTinh, chucVu)) {
            nhanVienBUS.docDanhSach();
            loadDataTblNhanVien();
        }
    }

    private void xuLyThemNhanVien() {
        if (cmbGioiTinh.getSelectedIndex() == 0) {
            new MyDialog("Hãy chọn giới tính!", MyDialog.ERROR_DIALOG);
            return;
        }
        String ho = txtHo.getText();
        String ten = txtTen.getText();
        String gioiTinh = cmbGioiTinh.getSelectedItem() + "";
        String chucVu = txtChucVu.getText();
        if (nhanVienBUS.themNhanVien(ho, ten, gioiTinh, chucVu)) {
            nhanVienBUS.docDanhSach();
            loadDataTblNhanVien();
        }
    }
    
    
    private void xuLyTimKiemNhanVien() {
        ArrayList<NhanVien> dsnv = nhanVienBUS.timNhanVien(txtTimNV.getText());
        dtmNhanVien.setRowCount(0);
        for (NhanVien nv : dsnv) {
            Vector<Object> vec = new Vector<>();
            vec.add(nv.getMaNV());
            vec.add(nv.getHo());
            vec.add(nv.getTen());
            vec.add(nv.getGioiTinh());
            vec.add(nv.getChucVu());
            int trangThai = taiKhoanBUS.getTrangThai(nv.getMaNV() + "");
            if (trangThai == 0) {
                vec.add("Khoá");
            }
            else if(trangThai == 1) {
                vec.add("Hiệu lực");
            }
            else {
                vec.add("Chưa có");
            }
            dtmNhanVien.addRow(vec);
        }
    }
    
    
    private void xuLyClickTblNhanVien() {
        int row = tblNhanVien.getSelectedRow();
        if (row > -1) {
            txtMaNV.setText(tblNhanVien.getValueAt(row, 0) + "");
            txtHo.setText(tblNhanVien.getValueAt(row, 1) + "");
            txtTen.setText(tblNhanVien.getValueAt(row, 2) + "");
            txtChucVu.setText(tblNhanVien.getValueAt(row, 4) + "");

            String gioiTinh = "";
            if ((tblNhanVien.getValueAt(row, 3) + "").equals("Nam")) {
                cmbGioiTinh.setSelectedIndex(1);
            } else {
                cmbGioiTinh.setSelectedIndex(2);
            }
        }
    }
    
    private void loadDataTblNhanVien() {  
        NhanVienBUS nhanVienBUS = new NhanVienBUS();
        ArrayList<NhanVien> dsnv = nhanVienBUS.getDanhSachNhanVien();
        dtmNhanVien= (DefaultTableModel) tblNhanVien.getModel();
        dtmNhanVien.setNumRows(0);
        for (NhanVien index : dsnv) {
            Vector<Object> vector = new Vector<>();
            vector.add((Object) index.getMaNV());
            vector.add((Object) index.getHo());
            vector.add((Object) index.getTen());
            vector.add((Object) index.getGioiTinh());
            vector.add((Object) index.getChucVu());
            int trangThai = taiKhoanBUS.getTrangThai(index.getMaNV() + "");
            if (trangThai == 0) {
                vector.add("Khoá");
            }
            else if(trangThai == 1) {
                vector.add("Hiệu lực");
            }
            else {
                vector.add("Chưa có");
            }
            dtmNhanVien.addRow(vector);
        }
        tblNhanVien.setModel(dtmNhanVien);
    }
    
    private void xuLyHienThiChiTietQuyen() {
        ArrayList<PhanQuyen> dsq = phanQuyenBUS.getListQuyen();
        PhanQuyen phanQuyen = new PhanQuyen();
        for (PhanQuyen pq : dsq) {
            if (pq.getQuyen().equals(cmbQuyen.getSelectedItem())) {
                phanQuyen.setQuyen(pq.getQuyen());
                phanQuyen.setNhapHang(pq.getNhapHang());
                phanQuyen.setQlSanPham(pq.getQlSanPham());
                phanQuyen.setQlNhanVien(pq.getQlNhanVien());
                phanQuyen.setQlKhachHang(pq.getQlKhachHang());
                phanQuyen.setThongKe(pq.getThongKe());
                break;
            }
        }
        ckbNhapHang.setSelected(false);
        ckbQLSanPham.setSelected(false);
        ckbQLNhanVien.setSelected(false);
        ckbQLKhachHang.setSelected(false);
        ckbThongKe.setSelected(false);
        if (phanQuyen.getNhapHang() == 1) {
            ckbNhapHang.setSelected(true);
        }
        if (phanQuyen.getQlSanPham() == 1) {
            ckbQLSanPham.setSelected(true);
        }
        if (phanQuyen.getQlNhanVien() == 1) {
            ckbQLNhanVien.setSelected(true);
        }
        if (phanQuyen.getQlKhachHang() == 1) {
            ckbQLKhachHang.setSelected(true);
        }
        if (phanQuyen.getThongKe() == 1) {
            ckbThongKe.setSelected(true);
        }
    }

    private void loadDataCmbQuyen() {
        PhanQuyenBUS phanQuyenBUS = new PhanQuyenBUS();
        phanQuyenBUS.docDanhSachQuyen();
        ArrayList<PhanQuyen> dsq = phanQuyenBUS.getListQuyen();
        cmbQuyen.removeAllItems();
        cmbQuyen.addItem("Chọn quyền");
        for (PhanQuyen pq : dsq) {
            cmbQuyen.addItem(pq.getQuyen());
        }
    }
    
    private void xuLyXoaQuyen() {
        if (cmbQuyen.getSelectedIndex() < 1) {
            new MyDialog("Chưa chọn nhóm quyền để xoá!", MyDialog.ERROR_DIALOG);
            return;
        }
        MyDialog dlg = new MyDialog("Bạn có chắc chắn muốn xoá?", MyDialog.WARNING_DIALOG);
        if (dlg.getAction() == MyDialog.CANCEL_OPTION) {
            return;
        }
        String tenQuyen = cmbQuyen.getSelectedItem() + "";
        boolean flag = phanQuyenBUS.xoaQuyen(tenQuyen);
        if (flag) {
            loadDataCmbQuyen();
        }
    }

    private void xuLyThemQuyen() {
        String tenQuyen = JOptionPane.showInputDialog("Nhập tên quyền");

        boolean flag = phanQuyenBUS.themQuyen(tenQuyen);
        if (flag) {
            loadDataCmbQuyen();
        }
    }

    private void xuLySuaQuyen() {
        if (cmbQuyen.getSelectedIndex() < 1) {
            new MyDialog("Chưa chọn nhóm quyền để sửa!", MyDialog.ERROR_DIALOG);
            return;
        }
        String tenQuyen = cmbQuyen.getSelectedItem() + "";
        int nhapHang = ckbNhapHang.isSelected() ? 1 : 0;
        int sanPham = ckbQLSanPham.isSelected() ? 1 : 0;
        int nhanVien = ckbQLNhanVien.isSelected() ? 1 : 0;
        int khachHang = ckbQLKhachHang.isSelected() ? 1 : 0;
        int thongKe = ckbThongKe.isSelected() ? 1 : 0;

        boolean flag = phanQuyenBUS.suaQuyen(tenQuyen, nhapHang, sanPham, nhanVien, khachHang, thongKe);
        if (flag) {
            loadDataCmbQuyen();
        }
    }
    
    private void xuLyResetMatKhau() {
        String maNV = txtMaNV.getText();
        if (maNV.trim().equals("")) {
            new MyDialog("Hãy chọn nhân viên!", MyDialog.ERROR_DIALOG);
            return;
        }
        DlgQuyen_MatKhau dialog = new DlgQuyen_MatKhau(maNV);
        dialog.setVisible(true);
    }

    private void xuLyCapTaiKhoan() {
        if (txtMaNV.getText().trim().equals("")) {
            new MyDialog("Hãy chọn nhân viên!", MyDialog.ERROR_DIALOG);
            return;
        }
        DlgCapTaiKhoan dialog = new DlgCapTaiKhoan(txtMaNV.getText());
        dialog.setVisible(true);
        loadDataTblNhanVien();
    }
    
    private void xulyReset(){
        loadDataTblNhanVien();
        txtMaNV.setText("");
        txtHo.setText("");
        txtTen.setText("");
        txtChucVu.setText("");
        txtTimNV.setText("");
        cmbGioiTinh.setSelectedIndex(0);
    }
    private void xulyKhoa()
    {
        TaiKhoanBUS tk = new TaiKhoanBUS();
        String maNV = txtMaNV.getText();
        if(maNV.trim().equals(""))
        {
            new MyDialog("Mã nhân viên đang trống!", MyDialog.ERROR_DIALOG);
        }
        else if(tk.getTrangThai(maNV) == 0)
        {
            tk.moKhoaTaiKhoan(maNV);
        }
        else if(tk.getTrangThai(maNV) == -1)
        {
            new MyDialog("Tài khoản chưa có hiệu lực! Vui lòng cấp tài khoản", MyDialog.ERROR_DIALOG);
            xuLyCapTaiKhoan();
        }
        else tk.khoaTaiKhoan(maNV);
        loadDataTblNhanVien();
    }
    
    private void ckbNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbNhapHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbNhapHangActionPerformed

    private void ckbQLSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbQLSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbQLSanPhamActionPerformed

    private void ckbThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbThongKeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbThongKeActionPerformed

    private void ckbQLNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbQLNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbQLNhanVienActionPerformed

    private void ckbQLKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbQLKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbQLKhachHangActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        xuLyClickTblNhanVien();
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void cmbQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbQuyenActionPerformed
        xuLyHienThiChiTietQuyen();
    }//GEN-LAST:event_cmbQuyenActionPerformed

    private void btnThemNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemNVMouseClicked
        xuLyThemNhanVien();
    }//GEN-LAST:event_btnThemNVMouseClicked

    private void btnSuaNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaNVMouseClicked
        xuLySuaNhanVien();
    }//GEN-LAST:event_btnSuaNVMouseClicked

    private void btnXoaNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaNVMouseClicked
        xuLyXoaNhanVien();
    }//GEN-LAST:event_btnXoaNVMouseClicked

    private void btnCapTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapTaiKhoanMouseClicked
        xuLyCapTaiKhoan();
    }//GEN-LAST:event_btnCapTaiKhoanMouseClicked

    private void btnResetQuyenMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetQuyenMatKhauMouseClicked
        xuLyResetMatKhau();
    }//GEN-LAST:event_btnResetQuyenMatKhauMouseClicked

    private void btnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {                                                  
        xuLyTimKiemNhanVien();
    }
    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        xulyReset();
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnThemQuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemQuyenMouseClicked
       xuLyThemQuyen();
    }//GEN-LAST:event_btnThemQuyenMouseClicked

    private void btnSuaQuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaQuyenMouseClicked
        xuLySuaQuyen();
    }//GEN-LAST:event_btnSuaQuyenMouseClicked

    private void btnXoaQuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaQuyenMouseClicked
         xuLyXoaQuyen();
    }//GEN-LAST:event_btnXoaQuyenMouseClicked

    private void btnKhoaTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhoaTaiKhoanMouseClicked
        // TODO add your handling code here:
        xulyKhoa();
    }//GEN-LAST:event_btnKhoaTaiKhoanMouseClicked
    
    private PhanQuyenBUS phanQuyenBUS = new PhanQuyenBUS();
    private NhanVienBUS nhanVienBUS = new NhanVienBUS();
    private TaiKhoanBUS taiKhoanBUS = new TaiKhoanBUS();
    private DefaultTableModel dtmNhanVien =new DefaultTableModel();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bpnThemQuyen;
    private javax.swing.JLabel btnCapTaiKhoan;
    private javax.swing.JLabel btnKhoaTaiKhoan;
    private javax.swing.JLabel btnReset;
    private javax.swing.JLabel btnResetQuyenMatKhau;
    private javax.swing.JLabel btnSuaNV;
    private javax.swing.JLabel btnSuaQuyen;
    private javax.swing.JLabel btnThemNV;
    private javax.swing.JLabel btnThemQuyen;
    private javax.swing.JLabel btnTimNV;
    private javax.swing.JLabel btnXoaNV;
    private javax.swing.JLabel btnXoaQuyen;
    private javax.swing.JCheckBox ckbNhapHang;
    private javax.swing.JCheckBox ckbQLKhachHang;
    private javax.swing.JCheckBox ckbQLNhanVien;
    private javax.swing.JCheckBox ckbQLSanPham;
    private javax.swing.JCheckBox ckbThongKe;
    private javax.swing.JComboBox<String> cmbGioiTinh;
    private javax.swing.JComboBox<String> cmbQuyen;
    private javax.swing.JPanel form_phanquyen;
    private javax.swing.JPanel form_quanlynhanvien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnCapTaiKhoan;
    private javax.swing.JPanel pnResetMatKhau;
    private javax.swing.JPanel pnSuaNV;
    private javax.swing.JPanel pnSuaQuyen;
    private javax.swing.JPanel pnThemNV;
    private javax.swing.JPanel pnTimNV;
    private javax.swing.JPanel pnXoaNV;
    private javax.swing.JPanel pnXoaQuyen;
    private MyCustom.MyTable tblNhanVien;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimNV;
    // End of variables declaration//GEN-END:variables
}
