/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLy.GUI;

import QuanLy.DTO.LoaiSP;
import QuanLy.DTO.HoaDon;
import QuanLy.DTO.SanPham;
import QuanLy.DTO.CTHoaDon;
import QuanLy.DTO.NhanVien;
import QuanLy.BUS.LoaiBUS;
import QuanLy.BUS.NhanVienBUS;
import QuanLy.BUS.HoaDonBUS;
import QuanLy.BUS.CTHoaDonBUS;
import QuanLy.BUS.DangNhapBUS;
import QuanLy.BUS.SanPhamBUS;

import MyCustom.MyDialog;
import MyCustom.MyTable;

import java.awt.*;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.io.*;
import java.text.*;
import java.util.*;
import javax.imageio.*;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.text.*;
/**
 *
 * @author Pero
 */
public class FormBanHang extends JPanel {
    
    public FormBanHang() {
        initComponents();
        loadDataTableSanPhamBan();
        loadDataComboboxLoaiBanSP();
        loadDataComboboxNhanVienBan();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnXuatHoaSonSP = new javax.swing.JPanel();
        btnXuatHoaDonSP = new javax.swing.JLabel();
        btnXoaSPGioHang = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_tongtien = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBanHang = new MyCustom.MyTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblGioHang = new MyCustom.MyTable();
        jLabel3 = new javax.swing.JLabel();
        txtMaSPBanHang = new javax.swing.JTextField();
        lblAnhSP = new javax.swing.JLabel();
        txtTenSPBanHang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbLoaiSPBanHang = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        spnSoLuongBanHang = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        txtDonGiaBanHang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbNhanVienBan = new javax.swing.JComboBox<>();
        pnThemVaoGio = new javax.swing.JPanel();
        btnThemVaoGio = new javax.swing.JLabel();
        btnReset = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1110, 720));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Danh sách sản phẩm");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Giỏ hàng");

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Tổng cộng: ");

        pnXuatHoaSonSP.setBackground(new java.awt.Color(51, 51, 51));
        pnXuatHoaSonSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnXuatHoaDonSP.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnXuatHoaDonSP.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatHoaDonSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnXuatHoaDonSP.setText("Xuất Hóa Đơn");
        btnXuatHoaDonSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXuatHoaDonSPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnXuatHoaSonSPLayout = new javax.swing.GroupLayout(pnXuatHoaSonSP);
        pnXuatHoaSonSP.setLayout(pnXuatHoaSonSPLayout);
        pnXuatHoaSonSPLayout.setHorizontalGroup(
            pnXuatHoaSonSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXuatHoaSonSPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnXuatHoaDonSP, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnXuatHoaSonSPLayout.setVerticalGroup(
            pnXuatHoaSonSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXuatHoaSonSPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnXuatHoaDonSP, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnXoaSPGioHang.setBackground(new java.awt.Color(173, 36, 36));
        btnXoaSPGioHang.setToolTipText("");
        btnXoaSPGioHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoaSPGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaSPGioHangMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Xóa ");
        jLabel13.setToolTipText("");

        javax.swing.GroupLayout btnXoaSPGioHangLayout = new javax.swing.GroupLayout(btnXoaSPGioHang);
        btnXoaSPGioHang.setLayout(btnXoaSPGioHangLayout);
        btnXoaSPGioHangLayout.setHorizontalGroup(
            btnXoaSPGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnXoaSPGioHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnXoaSPGioHangLayout.setVerticalGroup(
            btnXoaSPGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnXoaSPGioHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbl_tongtien.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbl_tongtien.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tongtien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_tongtien.setText(""+sum);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("VND");

        dtmSanPhamBan=new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Đơn giá", "Còn lại", "Chi tiết", "pic"
            }
        );
        tblBanHang.setModel(dtmSanPhamBan);
        tblBanHang.setRowHeight(35);
        loadDataTableSanPhamBan();
        tblBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBanHangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblBanHang);
        if (tblBanHang.getColumnModel().getColumnCount() > 0) {
            tblBanHang.getColumnModel().getColumn(0).setMaxWidth(75);
            tblBanHang.getColumnModel().getColumn(1).setMaxWidth(300);
            tblBanHang.getColumnModel().getColumn(2).setMaxWidth(150);
            tblBanHang.getColumnModel().getColumn(3).setMaxWidth(75);
            tblBanHang.getColumnModel().getColumn(4).setMaxWidth(75);
            tblBanHang.getColumnModel().getColumn(5).setMaxWidth(25);
        }

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Mã", "Tên sản phẩm", "SL", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGioHang.setRowHeight(45);
        tblGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGioHangMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblGioHang);
        if (tblGioHang.getColumnModel().getColumnCount() > 0) {
            tblGioHang.getColumnModel().getColumn(0).setMaxWidth(50);
            tblGioHang.getColumnModel().getColumn(1).setMaxWidth(150);
            tblGioHang.getColumnModel().getColumn(2).setMaxWidth(50);
            tblGioHang.getColumnModel().getColumn(3).setMaxWidth(100);
            tblGioHang.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Mã SP:");

        txtMaSPBanHang.setEditable(false);
        txtMaSPBanHang.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        txtMaSPBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSPBanHangActionPerformed(evt);
            }
        });

        lblAnhSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnhSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTenSPBanHang.setEditable(false);
        txtTenSPBanHang.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tên SP:");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Loại SP:");

        cmbLoaiSPBanHang.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        cmbLoaiSPBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLoaiSPBanHangActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Số lượng");

        spnSoLuongBanHang.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Đơn giá:");

        txtDonGiaBanHang.setEditable(false);
        txtDonGiaBanHang.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtDonGiaBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaBanHangActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nhân viên:");

        cmbNhanVienBan.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        cmbNhanVienBan.setForeground(new java.awt.Color(0, 0, 0));
        cmbNhanVienBan.setEnabled(false);

        pnThemVaoGio.setBackground(new java.awt.Color(51, 51, 51));
        pnThemVaoGio.setForeground(new java.awt.Color(255, 255, 255));
        pnThemVaoGio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnThemVaoGio.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnThemVaoGio.setForeground(new java.awt.Color(255, 255, 255));
        btnThemVaoGio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThemVaoGio.setText("Thêm vào giỏ hàng");
        btnThemVaoGio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemVaoGioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnThemVaoGioLayout = new javax.swing.GroupLayout(pnThemVaoGio);
        pnThemVaoGio.setLayout(pnThemVaoGioLayout);
        pnThemVaoGioLayout.setHorizontalGroup(
            pnThemVaoGioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemVaoGioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemVaoGio, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnThemVaoGioLayout.setVerticalGroup(
            pnThemVaoGioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemVaoGioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemVaoGio, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReset.setIcon(new javax.swing.ImageIcon(".\\image\\refresh.png")); // NOI18N
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(46, 46, 46)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTenSPBanHang)
                                            .addComponent(txtMaSPBanHang)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spnSoLuongBanHang)
                                            .addComponent(cmbLoaiSPBanHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7))
                                        .addGap(25, 25, 25)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDonGiaBanHang)
                                            .addComponent(cmbNhanVienBan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAnhSP, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnThemVaoGio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                    .addComponent(lbl_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(pnXuatHoaSonSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnXoaSPGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_tongtien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnXuatHoaSonSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaSPGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaSPBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenSPBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbLoaiSPBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnSoLuongBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDonGiaBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbNhanVienBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAnhSP, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnThemVaoGio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadDataComboboxLoaiBanSP() {
        cmbLoaiSPBanHang.removeAllItems();
        cmbLoaiSPBanHang.addItem("0 - Chọn loại");
        ArrayList<LoaiSP> dsl = loaiBUS.getDanhSachLoai();

        for (LoaiSP loai : dsl) {
            if (!loai.getTenLoai().equalsIgnoreCase("Nguyên liệu")) {
                cmbLoaiSPBanHang.addItem(loai.getMaLoai() + " - " + loai.getTenLoai());
            }
        }
    }

    
    
    DecimalFormat dcf = new DecimalFormat("###,###");
    

    private void loadDataTableSanPhamBan() {
        SanPhamBUS spBUS = new SanPhamBUS();
        ArrayList<SanPham> dssp = null;
        dtmSanPhamBan = (DefaultTableModel) tblBanHang.getModel();
        dtmSanPhamBan.setNumRows(0);
        if (cmbLoaiSPBanHang.getItemCount() > 0) {
            String loai = cmbLoaiSPBanHang.getSelectedItem() + "";
            String loaiArr[] = loai.split("-");
            String loaiSP = loaiArr[0].trim();

            if (loaiSP.equals("0")) {
                dssp = spBUS.getListSanPham();
            } else {
                dssp = spBUS.getSanPhamTheoLoai(loaiSP);
            }
        } else {
            dssp = spBUS.getListSanPham();
        }
        
        for (SanPham sp : dssp) {
            Vector<Object> vec = new Vector<>();
            vec.add((Object) sp.getMaSP());
            vec.add((Object) sp.getTenSP());
            vec.add(dcf.format((Object) sp.getDonGia()));
            vec.add(dcf.format((Object) sp.getSoLuong()));
            vec.add((Object) sp.getDonViTinh());
            vec.add((Object) sp.getHinhAnh());
            dtmSanPhamBan.addRow(vec);
        }
        dtmSanPhamBan.fireTableDataChanged();
        //tblBanHang.setModel(dtmSanPhamBan);

    }

    private void xuLyClickTblBanHang() {
        int row = tblBanHang.getSelectedRow();
        if (row > -1) {
            String ma = tblBanHang.getValueAt(row, 0) + "";
            String ten = tblBanHang.getValueAt(row, 1) + "";
            String donGia = tblBanHang.getValueAt(row, 2) + "";
            String anh = tblBanHang.getValueAt(row, 5) + "";
            int soLuong = Integer.parseInt(tblBanHang.getValueAt(row, 3) + "");
            if (soLuong < 1) {
                MyDialog dlg = new MyDialog("Sản phẩm đã hết hàng", MyDialog.ERROR_DIALOG);
                return;
            }

            SpinnerNumberModel modeSpinner = new SpinnerNumberModel(1, 1, soLuong, 1);
            spnSoLuongBanHang.setModel(modeSpinner);
            JFormattedTextField txtSpinner = ((JSpinner.NumberEditor) spnSoLuongBanHang.getEditor()).getTextField();
            ((NumberFormatter) txtSpinner.getFormatter()).setAllowsInvalid(false);
            txtSpinner.setEditable(false);
            txtSpinner.setHorizontalAlignment(JTextField.LEFT);

            txtMaSPBanHang.setText(ma);
            txtTenSPBanHang.setText(ten);
            txtDonGiaBanHang.setText(donGia);
            loadAnh(anh);
        }
    }
    
    private void loadAnh(String anh) {
        lblAnhSP.setIcon(getAnhSP(anh));
    }

    File fileAnhSP;

    private ImageIcon getAnhSP(String src) {
        src = src.trim().equals("") ? "default.png" : src;
        //Xử lý ảnh
        BufferedImage img = null;
        File fileImg = new File("image/SanPham/" + src);

        if (!fileImg.exists()) {
            src = "default.png";
            fileImg = new File("image/SanPham/" + src);
        }

        try {
            img = ImageIO.read(fileImg);
            fileAnhSP = new File("image/SanPham/" + src);
        } catch (IOException e) {
            fileAnhSP = new File("image/SanPham/default.png");
        }

        if (img != null) {
            Image dimg = img.getScaledInstance(200, 200, Image.SCALE_SMOOTH);

            return new ImageIcon(dimg);
        }
        return null;
    }
    
    private void xuLyClickTblGioHang() {
        int row = tblGioHang.getSelectedRow();
        if (row < 0) {
            return;
        }
        String ma = tblGioHang.getValueAt(row, 0) + "";
        loadAnh(spBUS.getAnh(ma));
    }
    
    private void xuLyThemVaoGioHang() {
        int row = tblBanHang.getSelectedRow();
        if (row < 0) {
            return;
        }
        String ma = txtMaSPBanHang.getText();
        String ten = txtTenSPBanHang.getText();
        String donGia = txtDonGiaBanHang.getText();
        int soLuong = Integer.parseInt(spnSoLuongBanHang.getValue() + "");
        int soLuongConLai = Integer.parseInt(tblBanHang.getValueAt(tblBanHang.getSelectedRow(), 3) + "");

        if (soLuong > soLuongConLai || soLuongConLai <= 0) {
            new MyDialog("Sản phẩm đã hết hàng", MyDialog.ERROR_DIALOG);
            return;
        }
        txtMaSPBanHang.setText("");
        txtTenSPBanHang.setText("");
        txtDonGiaBanHang.setText("");
        spnSoLuongBanHang.setValue(0);
        
        if (ma.trim().equalsIgnoreCase(""))
             return;
         int key = Integer.parseInt(ma);
        for (int i = 0; i < tblGioHang.getRowCount(); i++) {
            int maTbl = Integer.parseInt(tblGioHang.getValueAt(i, 0) + "");
            if (maTbl == key) {
                int soLuongAdd = Integer.parseInt(tblGioHang.getValueAt(i, 2) + "");
                soLuongAdd += soLuong;
                donGia = donGia.replace(",", "");
                int donGiaSP = Integer.parseInt(donGia);

                tblGioHang.setValueAt(soLuongAdd, i, 2);
                tblGioHang.setValueAt(dcf.format(soLuongAdd * donGiaSP), i, 4);


                sum=Sum();
                //Load tong tien
                lbl_tongtien.setText(""+sum);

                
                // cập nhật lại số lượng trong db
                spBUS.capNhatSoLuongSP(key, -soLuong);
                spBUS.docListSanPham();
                loadDataTableSanPhamBan();
                return;
            }
        }
        dtmGioHang = (DefaultTableModel) tblGioHang.getModel();
        //dtmGioHang.setNumRows(0);
        Vector<Object> vec = new Vector<>();
        vec.add((Object) ma);
        vec.add((Object) ten);
        vec.add((Object) soLuong);
        vec.add((Object) donGia);
        donGia = donGia.replace(",", "");
        int donGiaSP = Integer.parseInt(donGia);
        vec.add(dcf.format((Object) (soLuong * donGiaSP))); 
        dtmGioHang.addRow(vec);
        dtmGioHang.fireTableDataChanged();
        tblGioHang.setModel(dtmGioHang);

        sum=Sum();
        //Load tong tien
        lbl_tongtien.setText(""+sum);

        
        // cập nhật lại số lượng trong db
        spBUS.capNhatSoLuongSP(key, -soLuong);
        spBUS.docListSanPham(); 
        loadDataTableSanPhamBan();
    }

    private void xuLyXoaSPGioHang() {
        int row = tblGioHang.getSelectedRow();
        if (row > -1) {
            int ma = Integer.parseInt(tblGioHang.getValueAt(row, 0) + "");
            int soLuong = Integer.parseInt(tblGioHang.getValueAt(row, 2) + "");
            spBUS.capNhatSoLuongSP(ma, soLuong);
            dtmGioHang.removeRow(row);
            sum=Sum();
            //Load tong tien
            lbl_tongtien.setText(""+sum);
            loadDataTableSanPhamBan();
        }
    }

    private void xuLyXoaSPGioHang(int row) {
        if (row > -1) {
            int ma = Integer.parseInt(tblGioHang.getValueAt(row, 0) + "");
            int soLuong = Integer.parseInt(tblGioHang.getValueAt(row, 2) + "");
            spBUS.capNhatSoLuongSP(ma, soLuong);
            sum=Sum();
            //Load tong tien
            lbl_tongtien.setText(""+sum);
            loadDataTableSanPhamBan();
        }
    }

    private void xuLyXuatHoaDonBanHang() {
        ArrayList<Vector> dsGioHang = new ArrayList<>();
        int row = tblGioHang.getRowCount();
        if (row == 0) return;
        int tongTien = 0;
        for (int i = 0; i < row; i++) {
            Vector<Object> vec = new Vector<>();
            vec.add(tblGioHang.getValueAt(i, 0));
            vec.add(tblGioHang.getValueAt(i, 1));
            vec.add(tblGioHang.getValueAt(i, 2));
            vec.add(tblGioHang.getValueAt(i, 3));
            vec.add(tblGioHang.getValueAt(i, 4));
            tongTien += Integer.parseInt((tblGioHang.getValueAt(i, 4) + "").replace(",", ""));
            dsGioHang.add(vec);
        }

        XuatHoaDonGUI hoaDonUI = new XuatHoaDonGUI(dsGioHang, tongTien, cmbNhanVienBan.getSelectedItem());
        hoaDonUI.setVisible(true);
        if (hoaDonUI.checkBanHang) {
            dtmGioHang.setRowCount(0);
        }
    }
    
    private void xuLyResetData() {
        loadDataComboboxLoaiBanSP();
        cmbLoaiSPBanHang.setSelectedIndex(0);
        loadDataComboboxNhanVienBan();
    }
    
    private void loadDataComboboxNhanVienBan() {
        cmbNhanVienBan.removeAllItems();
        ArrayList<NhanVien> dsnv = nvBUS.getDanhSachNhanVien();
        if (dsnv != null) {
            for (NhanVien nv : dsnv) {
                cmbNhanVienBan.addItem(nv.getMaNV() + " - " + nv.getHo() + " " + nv.getTen());
            }
        }

        for (int i = 0; i < cmbNhanVienBan.getItemCount(); i++) {
            String[] cmbValue = cmbNhanVienBan.getItemAt(i).split(" - ");
            if (cmbValue[0].equals(DangNhapBUS.taiKhoanLogin.getMaNhanVien() + "")) {
                cmbNhanVienBan.setSelectedIndex(i);
                break;
            }
        }
    }
    private int Sum()
    {
        int tongtien=0;
        for(int i=0;i<tblGioHang.getRowCount();i++)
        {
            String thanhtien = dtmGioHang.getValueAt(i,4).toString();
            thanhtien = thanhtien.replace(",", "");
            tongtien += Integer.parseInt(thanhtien);
        }
        return tongtien;
    }
    
    private void txtMaSPBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSPBanHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSPBanHangActionPerformed

    private void txtDonGiaBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaBanHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaBanHangActionPerformed

    private void tblBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBanHangMouseClicked
        xuLyClickTblBanHang();
    }//GEN-LAST:event_tblBanHangMouseClicked

    private void cmbLoaiSPBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLoaiSPBanHangActionPerformed
        loadDataTableSanPhamBan();
    }//GEN-LAST:event_cmbLoaiSPBanHangActionPerformed

    private void btnXoaSPGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaSPGioHangMouseClicked
        xuLyXoaSPGioHang();
    }//GEN-LAST:event_btnXoaSPGioHangMouseClicked

    private void btnThemVaoGioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemVaoGioMouseClicked
        xuLyThemVaoGioHang();
    }//GEN-LAST:event_btnThemVaoGioMouseClicked

    private void btnXuatHoaDonSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatHoaDonSPMouseClicked
        xuLyXuatHoaDonBanHang();
    }//GEN-LAST:event_btnXuatHoaDonSPMouseClicked

    private void tblGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGioHangMouseClicked
        xuLyClickTblGioHang();
    }//GEN-LAST:event_tblGioHangMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        xuLyResetData();
    }//GEN-LAST:event_btnResetMouseClicked
    
    private SanPhamBUS spBUS = new SanPhamBUS();
    private NhanVienBUS nvBUS = new NhanVienBUS();
    private LoaiBUS loaiBUS = new LoaiBUS();
    DefaultTableModel dtmSanPhamBan, dtmGioHang;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnReset;
    private javax.swing.JLabel btnThemVaoGio;
    private javax.swing.JPanel btnXoaSPGioHang;
    private javax.swing.JLabel btnXuatHoaDonSP;
    private javax.swing.JComboBox<String> cmbLoaiSPBanHang;
    private javax.swing.JComboBox<String> cmbNhanVienBan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAnhSP;
    private javax.swing.JLabel lbl_tongtien;
    private javax.swing.JPanel pnThemVaoGio;
    private javax.swing.JPanel pnXuatHoaSonSP;
    private javax.swing.JSpinner spnSoLuongBanHang;
    private MyCustom.MyTable tblBanHang;
    private MyCustom.MyTable tblGioHang;
    private javax.swing.JTextField txtDonGiaBanHang;
    private javax.swing.JTextField txtMaSPBanHang;
    private javax.swing.JTextField txtTenSPBanHang;
    private int sum =0;
    // End of variables declaration//GEN-END:variables
}
