/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLy.GUI;

/**
 *
 * @author Pero
 */
public class Panel_Menu extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Menu
     */
    public Panel_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menu_banhang = new javax.swing.JPanel();
        icon_cart = new javax.swing.JLabel();
        txt_banhang = new javax.swing.JLabel();
        menu_hoadon = new javax.swing.JPanel();
        icon_cart9 = new javax.swing.JLabel();
        txt_banhang9 = new javax.swing.JLabel();
        menu_sanpham = new javax.swing.JPanel();
        icon_cart10 = new javax.swing.JLabel();
        txt_banhang10 = new javax.swing.JLabel();
        menu_loaisanpham = new javax.swing.JPanel();
        icon_cart11 = new javax.swing.JLabel();
        txt_banhang11 = new javax.swing.JLabel();
        menu_nhaphang = new javax.swing.JPanel();
        icon_cart12 = new javax.swing.JLabel();
        txt_banhang12 = new javax.swing.JLabel();
        menu_khachhang = new javax.swing.JPanel();
        icon_cart13 = new javax.swing.JLabel();
        txt_banhang13 = new javax.swing.JLabel();
        menu_khuyenmai = new javax.swing.JPanel();
        icon_cart14 = new javax.swing.JLabel();
        txt_banhang14 = new javax.swing.JLabel();
        menu_nhanvien = new javax.swing.JPanel();
        icon_cart15 = new javax.swing.JLabel();
        txt_banhang15 = new javax.swing.JLabel();
        menu_thongke = new javax.swing.JPanel();
        icon_cart16 = new javax.swing.JLabel();
        txt_banhang16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(17, 16, 16));
        setPreferredSize(new java.awt.Dimension(250, 800));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pero\\Documents\\NetBeansProjects\\QuanLyCuaHang\\image\\Menu_logo.png")); // NOI18N

        menu_banhang.setBackground(new java.awt.Color(17, 16, 16));
        menu_banhang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icon_cart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cart.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pero\\Documents\\NetBeansProjects\\QuanLyCuaHang\\image\\icon_cart.png")); // NOI18N
        icon_cart.setMaximumSize(new java.awt.Dimension(48, 48));
        icon_cart.setPreferredSize(new java.awt.Dimension(48, 48));

        txt_banhang.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_banhang.setForeground(new java.awt.Color(255, 255, 255));
        txt_banhang.setText("Bán hàng");

        javax.swing.GroupLayout menu_banhangLayout = new javax.swing.GroupLayout(menu_banhang);
        menu_banhang.setLayout(menu_banhangLayout);
        menu_banhangLayout.setHorizontalGroup(
            menu_banhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_banhangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_cart, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_banhang, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menu_banhangLayout.setVerticalGroup(
            menu_banhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_banhangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu_banhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_banhang, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon_cart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        menu_hoadon.setBackground(new java.awt.Color(17, 16, 16));
        menu_hoadon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icon_cart9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cart9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pero\\Documents\\NetBeansProjects\\QuanLyCuaHang\\image\\icon_bill.png")); // NOI18N
        icon_cart9.setMaximumSize(new java.awt.Dimension(48, 48));
        icon_cart9.setPreferredSize(new java.awt.Dimension(48, 48));

        txt_banhang9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_banhang9.setForeground(new java.awt.Color(255, 255, 255));
        txt_banhang9.setText("Hóa đơn");

        javax.swing.GroupLayout menu_hoadonLayout = new javax.swing.GroupLayout(menu_hoadon);
        menu_hoadon.setLayout(menu_hoadonLayout);
        menu_hoadonLayout.setHorizontalGroup(
            menu_hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_hoadonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_cart9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_banhang9, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menu_hoadonLayout.setVerticalGroup(
            menu_hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_hoadonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu_hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(icon_cart9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_banhang9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        menu_sanpham.setBackground(new java.awt.Color(17, 16, 16));
        menu_sanpham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icon_cart10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cart10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pero\\Documents\\NetBeansProjects\\QuanLyCuaHang\\image\\icon_product.png")); // NOI18N
        icon_cart10.setMaximumSize(new java.awt.Dimension(48, 48));
        icon_cart10.setPreferredSize(new java.awt.Dimension(48, 48));

        txt_banhang10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_banhang10.setForeground(new java.awt.Color(255, 255, 255));
        txt_banhang10.setText("Sản phẩm");

        javax.swing.GroupLayout menu_sanphamLayout = new javax.swing.GroupLayout(menu_sanpham);
        menu_sanpham.setLayout(menu_sanphamLayout);
        menu_sanphamLayout.setHorizontalGroup(
            menu_sanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_sanphamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_cart10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_banhang10, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menu_sanphamLayout.setVerticalGroup(
            menu_sanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_sanphamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu_sanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_cart10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_banhang10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        menu_loaisanpham.setBackground(new java.awt.Color(17, 16, 16));
        menu_loaisanpham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icon_cart11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cart11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pero\\Documents\\NetBeansProjects\\QuanLyCuaHangNEW\\image\\icon_grid.png")); // NOI18N
        icon_cart11.setMaximumSize(new java.awt.Dimension(48, 48));
        icon_cart11.setPreferredSize(new java.awt.Dimension(48, 48));

        txt_banhang11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_banhang11.setForeground(new java.awt.Color(255, 255, 255));
        txt_banhang11.setText("Loại sản phẩm");

        javax.swing.GroupLayout menu_loaisanphamLayout = new javax.swing.GroupLayout(menu_loaisanpham);
        menu_loaisanpham.setLayout(menu_loaisanphamLayout);
        menu_loaisanphamLayout.setHorizontalGroup(
            menu_loaisanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_loaisanphamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_cart11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_banhang11, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menu_loaisanphamLayout.setVerticalGroup(
            menu_loaisanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_loaisanphamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu_loaisanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(icon_cart11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_banhang11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        menu_nhaphang.setBackground(new java.awt.Color(17, 16, 16));
        menu_nhaphang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icon_cart12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cart12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pero\\Documents\\NetBeansProjects\\QuanLyCuaHang\\image\\icon_supply.png")); // NOI18N
        icon_cart12.setMaximumSize(new java.awt.Dimension(48, 48));
        icon_cart12.setPreferredSize(new java.awt.Dimension(48, 48));

        txt_banhang12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_banhang12.setForeground(new java.awt.Color(255, 255, 255));
        txt_banhang12.setText("Nhập hàng");

        javax.swing.GroupLayout menu_nhaphangLayout = new javax.swing.GroupLayout(menu_nhaphang);
        menu_nhaphang.setLayout(menu_nhaphangLayout);
        menu_nhaphangLayout.setHorizontalGroup(
            menu_nhaphangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_nhaphangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_cart12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_banhang12, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menu_nhaphangLayout.setVerticalGroup(
            menu_nhaphangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_nhaphangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu_nhaphangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_banhang12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon_cart12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        menu_khachhang.setBackground(new java.awt.Color(17, 16, 16));
        menu_khachhang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icon_cart13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cart13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pero\\Documents\\NetBeansProjects\\QuanLyCuaHang\\image\\icon_customer.png")); // NOI18N
        icon_cart13.setMaximumSize(new java.awt.Dimension(48, 48));
        icon_cart13.setPreferredSize(new java.awt.Dimension(48, 48));

        txt_banhang13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_banhang13.setForeground(new java.awt.Color(255, 255, 255));
        txt_banhang13.setText("Khách hàng");

        javax.swing.GroupLayout menu_khachhangLayout = new javax.swing.GroupLayout(menu_khachhang);
        menu_khachhang.setLayout(menu_khachhangLayout);
        menu_khachhangLayout.setHorizontalGroup(
            menu_khachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_khachhangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_cart13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_banhang13, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menu_khachhangLayout.setVerticalGroup(
            menu_khachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_khachhangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu_khachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_banhang13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon_cart13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        menu_khuyenmai.setBackground(new java.awt.Color(17, 16, 16));
        menu_khuyenmai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icon_cart14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cart14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pero\\Documents\\NetBeansProjects\\QuanLyCuaHang\\image\\icon_promo.png")); // NOI18N
        icon_cart14.setMaximumSize(new java.awt.Dimension(48, 48));
        icon_cart14.setPreferredSize(new java.awt.Dimension(48, 48));

        txt_banhang14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_banhang14.setForeground(new java.awt.Color(255, 255, 255));
        txt_banhang14.setText("Khuyến mãi");

        javax.swing.GroupLayout menu_khuyenmaiLayout = new javax.swing.GroupLayout(menu_khuyenmai);
        menu_khuyenmai.setLayout(menu_khuyenmaiLayout);
        menu_khuyenmaiLayout.setHorizontalGroup(
            menu_khuyenmaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_khuyenmaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_cart14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_banhang14, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menu_khuyenmaiLayout.setVerticalGroup(
            menu_khuyenmaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_khuyenmaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu_khuyenmaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_banhang14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon_cart14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        menu_nhanvien.setBackground(new java.awt.Color(17, 16, 16));
        menu_nhanvien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icon_cart15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cart15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pero\\Documents\\NetBeansProjects\\QuanLyCuaHang\\image\\icon_user.png")); // NOI18N
        icon_cart15.setMaximumSize(new java.awt.Dimension(48, 48));
        icon_cart15.setPreferredSize(new java.awt.Dimension(48, 48));

        txt_banhang15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_banhang15.setForeground(new java.awt.Color(255, 255, 255));
        txt_banhang15.setText("Nhân viên");

        javax.swing.GroupLayout menu_nhanvienLayout = new javax.swing.GroupLayout(menu_nhanvien);
        menu_nhanvien.setLayout(menu_nhanvienLayout);
        menu_nhanvienLayout.setHorizontalGroup(
            menu_nhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_nhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_cart15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_banhang15, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menu_nhanvienLayout.setVerticalGroup(
            menu_nhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_nhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu_nhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_banhang15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon_cart15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        menu_thongke.setBackground(new java.awt.Color(17, 16, 16));
        menu_thongke.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        icon_cart16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cart16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pero\\Documents\\NetBeansProjects\\QuanLyCuaHang\\image\\icon_chart.png")); // NOI18N
        icon_cart16.setMaximumSize(new java.awt.Dimension(48, 48));
        icon_cart16.setPreferredSize(new java.awt.Dimension(48, 48));

        txt_banhang16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_banhang16.setForeground(new java.awt.Color(255, 255, 255));
        txt_banhang16.setText("Thống kê");

        javax.swing.GroupLayout menu_thongkeLayout = new javax.swing.GroupLayout(menu_thongke);
        menu_thongke.setLayout(menu_thongkeLayout);
        menu_thongkeLayout.setHorizontalGroup(
            menu_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_thongkeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_cart16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_banhang16, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menu_thongkeLayout.setVerticalGroup(
            menu_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_thongkeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_banhang16, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon_cart16, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu_banhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu_hoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu_sanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu_loaisanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu_nhaphang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu_khachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu_khuyenmai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu_nhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu_thongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_banhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_hoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_sanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_loaisanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_nhaphang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_khuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_nhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_thongke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon_cart;
    private javax.swing.JLabel icon_cart10;
    private javax.swing.JLabel icon_cart11;
    private javax.swing.JLabel icon_cart12;
    private javax.swing.JLabel icon_cart13;
    private javax.swing.JLabel icon_cart14;
    private javax.swing.JLabel icon_cart15;
    private javax.swing.JLabel icon_cart16;
    private javax.swing.JLabel icon_cart9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel menu_banhang;
    private javax.swing.JPanel menu_hoadon;
    private javax.swing.JPanel menu_khachhang;
    private javax.swing.JPanel menu_khuyenmai;
    private javax.swing.JPanel menu_loaisanpham;
    private javax.swing.JPanel menu_nhanvien;
    private javax.swing.JPanel menu_nhaphang;
    private javax.swing.JPanel menu_sanpham;
    private javax.swing.JPanel menu_thongke;
    private javax.swing.JLabel txt_banhang;
    private javax.swing.JLabel txt_banhang10;
    private javax.swing.JLabel txt_banhang11;
    private javax.swing.JLabel txt_banhang12;
    private javax.swing.JLabel txt_banhang13;
    private javax.swing.JLabel txt_banhang14;
    private javax.swing.JLabel txt_banhang15;
    private javax.swing.JLabel txt_banhang16;
    private javax.swing.JLabel txt_banhang9;
    // End of variables declaration//GEN-END:variables
}
